### ISSUE TITLE
Question regarding dependencies

### ISSUE THREAD

**Issue by narner** [simonwsw/deep-soli#10]
Hello, in the readme, it's stated that [mattorch](https://github.com/clementfarabet/lua---mattorch) is outdated/no longer maintained.

Is there another library that could be used in it's place? I've been trying to install mattorch, and have been unsuccessful so far. 

Thank you!

**Comment by simonwsw** [comment]
You can use the [fb-mattorch](https://github.com/facebook/fblualib/tree/master/fblualib/mattorch) from Facebook
