### ISSUE TITLE
Request - vm image or docker container

### ISSUE THREAD

**Issue by narner** [simonwsw/deep-soli#11]
Hi again, 

Would it be possible to create an Ubuntu VM image or a Docker container with all the dependencies included? I've been generally having a pretty difficult time with installing everything needed / getting started. Appreciate any help.

Thank you!

**Comment by graulef** [comment]
Hi!
Sorry for the late response. I am currently working on a shared server in a lab in NTU and the OS is shared, so I cannot make an image without risking to publish sensible data. With what exactly are you struggling?
Cheers

**Comment by narner** [comment]
Hey there, no worries!
Gotchya - I'm actually also a member of the Soli Alpha Dev program, and have my own sensor. I'd like to use your work as the basis for doing some more real-time gesture recognition. Would you be able to chat more over email? nicholasarner (at) gmail (dot) com. 
Thanks!

**Comment by simonwsw** [comment]
Sorry, there's no VM/docker images. However, let me know if there's any problem getting the dependencies.

**Comment by nuwanarti** [comment]
I'm having trouble with installing H5Cpp on ubuntu 16.04, it would be a great help if there is any docker image
