### ISSUE TITLE
Creating own network

### ISSUE THREAD

**Issue by graulef** [simonwsw/deep-soli#13]
I would like to gain further insight into the process of training and therefore tried to create my own network and train it. However, I am struggling with implementing the LTSM functions and combining the CNN with the RNN. Could you publish the code to create the pretrained net that is given in the repo? If this is not possible (due to privacy/protecting the ideas) I of course understand

**Comment by simonwsw** [comment]
Sorry, publishing the training code was not part of the plan. However, the network configuration are published in the paper. When you run the evaluation code in the repository, the Torch network details will be printed to the console. You can easily figure out what layers and parameters are there to make the network work.
