### ISSUE TITLE
Question: Dimensions of input data

### ISSUE THREAD

**Issue by graulef** [simonwsw/deep-soli#14]
I am a bit confused by the first layer of the CNN. As far as I unterstand, the first layer (SpatialConvolution) takes in 4 planes of 2D image data (RDI), runs a 2D convolution on all the 4 layers and outputs something with 32 planes.

Two questions one this:
Why is the output so deep? (I know this question is really general and probably basic)
Why are the input images only 2D? After all, they themselves are RGB, right? So they should be 3D too. Or is everything converted to B/W during the generation of the meanfile?

Thanks in advance!

**Comment by graulef** [comment]
I just noticed that in the paper, the resolution of the RDIs is said to be 224x224 pixels. However, in the code provided here it is 32x32. Is there any specific reason for this difference?

**Comment by simonwsw** [comment]
> Why is the output so deep?

This helps to extract different features of the original input.

> Why are the input images only 2D?

The Range-Doppler Images are 2D only. It's not taken from RGB camera.

> 224 * 224 or 32 * 32

The resolution of RDIs is 32 * 32. The 224 * 224 interpolated input is used for performance comparison with VGG nets.

**Comment by graulef** [comment]
Thank you for your answers!
