### ISSUE TITLE
Questions about dataset 

### ISSUE THREAD

**Issue by deeplive** [simonwsw/deep-soli#2]
Hello, I want to know overall organization of your dataset.

For example, there are 50 files with a filename starting with 0_0_ and 25 files with a filename starting with 0_2_.

Why they are different? 

Also, I couldn't understand why there are  275 files with a filename starting with 11_15_. 

What does the gesture ID 11 mean in your dataset? 

I thought you considered 11 different gestures so that the gesture ID value is between 0 and 10.   

Thank you.

**Comment by simonwsw** [comment]
I Update the readme and add a few lines about the dataset arrangement. 

In short, the `2` in file name like `0_2_*` means the gesture collection session ID. It could be a session collected by different people or different session of a same people. Different session could have different number of files.

> - 11 (gestures) * 25 (instances) * 10 (users) for cross user evaluation: session 2 (25), 3 (25), 5 (25), 6 (25), 8 (25), 9 (25), 10 (25), 11 (25), 12 (25), 13 (25).
> - 11 (gestures) * (50 (instances) * 4 (sessions) + 25 (instances) * 2 (sessions)) for single user cross session evaluation: session 0 (50), 1 (50), 4 (50), 7 (50), 13 (25), 14 (25).

Gesture ID 11 is background class. I suggest you collect your own background class for proper training.
